### PR TITLE
Goals

### LINKED ISSUE #2: Goals + Stretch Goals
Complete text for goals and stretch goals

### PR DESCRIPTION
**Pull request by KyleJMcMaster**
closes #2

### CODE REVIEW

**Comment by KyleJMcMaster** [comment]
Can either force or drop changes to the pdf... either way the actions will overwrite it.

**Comment by matpetro** [comment]
A few comments:
- "Users of the system are interested in getting an appropriate return for their investment". For this line, are you talking about the customers who pay for the service or users who label? If the former then I think that distinction should be made for clarity.
- There is mention of uploading photos, but I thought we had to handle obtaining the needed photos on our end (This could just be a misunderstanding on my part)

**Comment by KyleJMcMaster** [comment]
> A few comments:
> 
> * "Users of the system are interested in getting an appropriate return for their investment". For this line, are you talking about the customers who pay for the service or users who label? If the former then I think that distinction should be made for clarity.

**Good point - will do**
> * There is mention of uploading photos, but I thought we had to handle obtaining the needed photos on our end (This could just be a misunderstanding on my part)

**I believe we intend to allow users to upload images for processing. @OlegGlo can you remind me what you were thinking? We can also make this more ambiguous for now while we refine our design.**

**Comment by matpetro** [comment]
With relation to image upload, Oleg mentioned that most likely both image upload by the customer and image sourcing on our end for the customer is part of the plans. Not sure if that effects anything you wrote

**Pull request merged**
